### ISSUE TITLE
Consider adding height prop to `Box`

### ISSUE THREAD

**Issue by broox9** [pricelinelabs/design-system#101]
The `Box` Component doesn't accept a `height` prop.  Not sure if that is purposeful or not, but I would be happy to add it.

**Comment by jxnblk** [comment]
We generally shouldn't be using `height` much in CSS, so I'd rather not have it as a prop. Setting a fixed height on a container can lead to its contents overflowing and is a common cause of "CSS bugs". Generally you're better off using `min-height` instead so that when content flows with the document, the element takes up as much space as needed. For ensuring that sibling elements share a common height, using flexbox layout is a better option. For content, such as images and icons, height is absolutely fine to use, but I don't want to encourage setting heights on containers

**Comment by jxnblk** [comment]
Closing this out for now, but feel free to bring this up again if it's an important issue for you team
