### ISSUE TITLE
Refactor Hide to not use max-width

### ISSUE THREAD

**Issue by jes708** [pricelinelabs/design-system#151]
`<Hide />` should use `min-width` only breakpoints to prevent gaps.  There is a gap at 768px for instance.

**Comment by jxnblk** [comment]
I think we should still use max-width media queries here to keep with the current behavior (HotelListing makes liberal use of this component). I tend to avoid using components like this to show and hide elements across breakpoints, since that's not something you do very often with responsive web design. We *can* compensate for the gap by setting the max-width media queries to a decimal value, e.g. `31.99em` instead of `32em`
