### ISSUE TITLE
Add exporting single Icons in addition to the Icon component

### ISSUE THREAD

**Issue by hakimelek** [pricelinelabs/design-system#179]
Webpack bundle analyzer results when consuming the design system components
![image](https://user-images.githubusercontent.com/1974993/34303094-e35dce3c-e701-11e7-8a58-c30ccb96a833.png)

**Comment by 747823** [comment]
This is super important if you're trying to optimize your app's load time, because right now if you import the Icon component you get the entire icons.json, which is about 80 kb parsed. Ouch... I don't think the Icon component should be used at all for that reason.

**Comment by jxnblk** [comment]
Missed this comment before, but I would *not* recommend importing from the `dist` folder. We certainly should add some improvements for tree-shakability and split up the Icon json, but things like the internal folder structure of a package should be treated as an internal API and changing the name of the `dist` folder would generally not be considered a breaking change, but if you import from there, your application might break.

This is the purpose of the package.json `main` field, and there are other things you can do in your application bundler to improve how it handles tree shaking. 

As for the `icons.json` file, webpack 4 supports tree shaking in JSON, so this might not be an issue in a few months

**Comment by 747823** [comment]
@jxnblk I understand that reasoning, because yeah the only API that should officially be supported is whatever we export from the file specified in the package.json's main. Totally agree with that, if the app is importing something from the internal file structure, changing it would not be considered a breaking change as long as the outside API is the same.

However do you have an example of how to make the host app tree-shake the unused modules while importing directly from the main entry point? All my tests where I use the 'import {} from ''` syntax do not work, presumably because only es import/exports are supported for tree shaking, while the main dist file has been transpiled to have `require` everywhere. And there is no way for the bundler to know whether each `require` is actually being used or not, as it can be called while the code is evaluated under different conditions...

I don't see how any type of tree shaking could apply to the current model for Icon, because the name is a prop which you can change dynamically in the application using the design system. So i.e. with the current model I could have my app switch the icon's name prop from "arrowDown" to "arrowUp", and that would trigger a new icon to render. For the component to support that it will always have to import the whole icons.json, even with tree shaking, since the bundler won't know whether the app is changing the prop or not. So I still think we should rethink the architecture of the component, unless there's some new and magical dynamic splitting for imported modules that I don't know about :)

**Comment by unscsprt** [comment]
@BeniCheni Can we close this issue?

**Comment by BeniCheni** [comment]
We can close, @unscsprt, since pcln-icon has been published in full swing. We can log separate issues for any further observation(s).
